{% set name = "rocketry" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/rocketry-{{ version }}.tar.gz
  sha256: 11d1fb3d2856c5b2727bb4814c4f2bfbd2803067eebeac872d34a4c7a6756825

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - pydantic
    - python >={{ python_min }}
    - python-dateutil
    - redbird >=0.5.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - rocketry
#  commands:
# Pip check not functioning correctly disabling for now
#    - pip check
#  requires:
#    - pip

about:
  home: https://github.com/Miksus/rocketry
  doc_url: https://rocketry.readthedocs.io/en/stable/
  summary: Advanced scheduling framework
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
